apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
name: argocd-server
images:
  - name: argocd-image-updater.argoproj.io/image-list: some/image:v2.1.3
   

resources:
- nginx-deployment.yaml
- nginx-svc.yaml
